# Step 1: Use a Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install Python dependencies
COPY ./backend/requirements.txt /app/
RUN pip install  -r requirements.txt

# Copy the backend code into the container
COPY ./backend /app

# Expose port 8000 for the FastAPI app
EXPOSE 8000

# Command to start the FastAPI app using Uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
