[phases.build]
commands = [
  "cd frontend && npm install && npm run build",
  "cd backend && pip install -r requirements.txt",
  "mkdir -p backend/static && cp -r frontend/dist/* backend/static/"
]

[phases.start]
command = "cd backend && uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}"
