[env]
PORT = "3000" 

[services.backend]
  command = "docker-compose up backend" 
  [services.backend.build]
    dockerfile = "Dockerfile.backend"

[services.frontend]
  command = "docker-compose up frontend" 
  [services.frontend.build]
    dockerfile = "Dockerfile.frontend"
