# Railway.toml

[build]
commands = [
    "cd frontend && npm install && npm run build",
    "cd backend && pip install -r requirements.txt"
]

[start]
command = "cd backend && uvicorn app:app --host 0.0.0.0 --port ${PORT}"
