[build]
commands = [
    # Install and build frontend
    "cd frontend && npm install && npm run build",
    
    # Install Python dependencies for backend
    "cd backend && pip install -r requirements.txt"
]

[start]
# Start the backend
command = "cd backend && uvicorn app:app --reload
"
